apiVersion: v1
kind: Service
metadata:
  name: server-example-service
spec:
  type: ClusterIP
  selector:
    app: server-example
  ports:
  - name: server
    protocol: TCP
    port: 80
    targetPort: 8080