steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/server-example-deployment', 'server=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=kube01t'
images: ["gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"]
